name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get tag
      id: tag
      uses: devops-actions/action-get-tag@v1.0.3
      with:
        default: v0.0.0 # Optional: Default version when tag not found

    - name: Build docker image
      run: make docker-build VERSION=${{steps.tag.outputs.tag}}

    - name: Push docker image
      run: make docker-push VERSION=${{steps.tag.outputs.tag}}
